### ISSUE TITLE
Invalid ids (e.g. to a specific method) are not validated

### ISSUE THREAD

**Issue by HarrisonMc555** [deadlinks/cargo-deadlinks#52] opened 2020-05-25 15:47 UTC
If you have a link to an invalid page, deadlinks will detect it. However, if you have a link to a valid page but an invalid id, deadlinks will *not* detect it.

Would it be possible and reasonable to check the ids? It would be very helpful. Otherwise, I have to check all the links with ids manually.

# Example

```rust
/// This is created by the [`foo`] method.
///
/// # Typo in method name
/// [`foo`]: Bar.html#tymethod.boo
struct Foo {}

trait Bar {
    fn foo() -> Foo;
}
```

**Comment by jyn514** [comment] 2020-11-18 03:19
Duplicate of https://github.com/deadlinks/cargo-deadlinks/issues/7.

**Closed by jyn514** 2020-11-18 03:19 UTC
Labels: C-enhancement
